# always_for_in = true
# conditional_to_if = true
# format_docstrings = true
# import_to_using=true
# indent = 4
# normalize_line_endings = "unix"
# pipe_to_function_call=true
# remove_extra_newlines = true
# short_to_long_function_def=false
# whitespace_in_kwargs = true
# whitespace_ops_in_indices = true
# whitespace_typedefs = true
